from django.contrib import admin
from django.urls import path
from Teslead_application import views
# from Teslead_application.views import add_product 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.admin_login_page, name='admin_login'),
    # path('add-product/', views.add_product, name='add_product'),
    path('r12_login',views.r12_login_page, name='r12_login'),
    path('loginr12',views.loginr12, name='loginr12'),
    path('user_dashboard',views.user_dashboard, name='user_dashboard'),
    path('admin_dashboard',views.admin_dashboard, name='admin_dashboard'),
    path('admin_product',views.admin_product_view, name='admin_product'),
    path('admin_dashboardview',views.admin_dashboard_view, name='admin_dashboardview'),
    path('live_status/admin_dashboardview',views.admin_dashboard_view, name='ladmin_dashboardview'),
    path('r12_dashboardview',views.r12_dashboardview, name='r12_dashboardview'),
    path('admin_alarm_system',views.admin_alarm_system_view, name='admin_alarm_system'),
    path('admin_analytics',views.admin_analytics_view, name='admin_analytics'),
    path('admin_configuration',views.admin_configuration_view, name='admin_configuration'),
    path('admin_report',views.admin_report_view, name='admin_report'),
    path('r12_live_status',views.r12_live_status, name='r12_live_status'),
    path('alarm_system/', views.alarm_system_view, name='alarm_system'),
    path('test_details',views.test_details, name='test_details'),
    path('test_serial_form',views.test_serial_form, name='test_serial_form'),
    path('add_product',views.add_product, name='add_product'),
    path('live_status/airshellfunction',views.airshellfunction, name='airshellfunction'),
    path('live_status/airseatfunction',views.airseatfunction, name='airseatfunction'),
    path('live_status/hydroshellfunction',views.hydroshellfunction, name='hydroshellfunction'),
    path('live_status/hydroseatfunction',views.hydroseatfunction, name='hydroseatfunction'),
    path('live_status/get_pressure_analysis_data',views.get_pressure_analysis_data, name='get_pressure_analysis_data'),
    path('load_live_status',views.load_live_status, name='load_live_status'),
    path('live_status/cyclecompletefunctionadmin',views.cyclecompletefunctionadmin, name='cyclecompletefunctionadmin'),
    path('live_status/cyclecompletefunctionr12',views.cyclecompletefunctionr12, name='cyclecompletefunctionr12'),
    path('live_status/gettestingparameterdata',views.gettestingparameterdata, name='gettestingparameterdata'),
    path('live_status/getautomanual',views.getautomanual, name='getautomanual'),
    path('live_status/getalarmmessage',views.getalarmmessage, name='getalarmmessage'),
    path('live_status/gettestbuttonstatus',views.gettestbuttonstatus, name='gettestbuttonstatus'),
    path('updatereporttable',views.updatereporttable, name='updatereporttable'),
    path('getgraphdata',views.getgraphdata, name='getgraphdata'),
    path('getactionbuttonstatus',views.getactionbuttonstatus, name='getactionbuttonstatus'),
    path('updataconfigdata',views.updataconfigdata, name='updataconfigdata'),
    path('getconfigbadresult',views.getconfigbadresult, name='getconfigbadresult'),
    path('getconfiggoodresult',views.getconfiggoodresult, name='getconfiggoodresult'),
    path('checkhmiconnection',views.checkhmiconnection, name='checkhmiconnection'),
    path('checkr12connection',views.checkr12connection, name='checkr12connection'),
    path('checkalarmsystemconnection',views.checkalarmsystemconnection, name='checkalarmsystemconnection'),
    path('getproductbyid',views.getproductbyid, name='getproductbyid'),
    path('deleteproduct',views.deleteproduct, name='deleteproduct'),
    path('getalarmbyid',views.getalarmbyid, name='getalarmbyid'),
    path('addalarmtodatabase',views.addalarmtodatabase, name='addalarmtodatabase'),
    path('deletealarm',views.deletealarm, name='deletealarm'),
    path('temptest',views.temptest, name='temptest'),
    path('admin_test_serial',views.admin_test_serial, name='admin_test_serial'),
    path('getsizeclass',views.getsizeclass, name='getsizeclass'),
    path('checkautotestchange',views.checkautotestchange, name='checkautotestchange'),
    path('getactualpressuretime',views.getactualpressuretime, name='getactualpressuretime'),
    path('loopevent',views.loopevent, name='loopevent'),
    path('getproductsizeclass',views.getproductsizeclass, name='getproductsizeclass'),
    path('getavailabletests',views.getavailabletests, name='getavailabletests'),
    path('live_status_loop',views.live_status_loop, name='live_status_loop'),
    path('logout',views.logout, name='logout'),
    path('transferreasons',views.transferreasons, name='transferreasons'),
    path('getallreasons',views.getallreasons, name='getallreasons'),
    path('addreason',views.addreason, name='addreason'),
    path('transferreasonsadmin',views.transferreasonsadmin, name='transferreasonsadmin'),
    path('live_status/',views.live_status, name='live_status')
]
