# Generated by Django 5.0.6 on 2024-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teslead_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FIRST_NAME',
            new_name='FirstName',
        ),
        migrations.RenameModel(
            old_name='LAST_NAME',
            new_name='LastName',
        ),
        migrations.RenameModel(
            old_name='OPR_TOKEN',
            new_name='OPRToken',
        ),
        migrations.DeleteModel(
            name='CELL_ID',
        ),
    ]
